_BASE_: Base-COCO-PanopticSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "DecDec"
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  NUM_CLASSES: 133
  DECDEC:
    BACKBONE_NAME: 'resnet50'
    FREEZE_BACKBONE: False
    FEATURE_DIM: [2048,1024,512,256,256]
    PIXEL_DECODER_LAYERS: [1,5,1,1]
    TRANSFORMER_DECODER_LAYERS: [2,2,2,0]

    DEEP_SUPERVISION: True
    # NO_OBJECT_WEIGHT: 0.1
    # CLASS_WEIGHT: 2.0
    # MASK_WEIGHT: 5.0
    # DICE_WEIGHT: 5.0

    NO_OBJECT_WEIGHT: 1e-5
    CLASS_WEIGHT: 3.0
    DICE_WEIGHT: 3.0
    MASK_WEIGHT: 0.3
    INSDIS_WEIGHT: 1.0
    AUX_SEMANTIC_WEIGHT: 1.0
    USE_AUX_SEMANTIC_DECODER: False
    PIXEL_INSDIS_TEMPERATURE: 1.5
    PIXEL_INSDIS_SAMPLE_K: 4096
    AUX_SEMANTIC_TEMPERATURE: 2.0
    AUX_SEMANTIC_SAMPLE_K: 4096
    MASKING_VOID_PIXEL: True
    SHARE_FINAL_MATCHING: True
    
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    SIZE_DIVISIBILITY: 32
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: True
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
INPUT:
  IMAGE_SIZE: 256
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256

  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_panoptic_lsj"